sudo: required
services:
    - docker

before_install:
    - docker build -t tarunk/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true tarunk/react-test npm test

after_success:
    - docker build -t tarunk/multi-client ./client
    - docker build -t tarunk/multi-nginx ./nginx
    - docker build -t tarunk/multi-server ./server
    - docker build -t tarunk/multi-worker ./worker
    # Login to docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take those images and push them to docker hub
    - docker push tarunk/multi-client
    - docker push tarunk/multi-nginx 
    - docker push tarunk/multi-server
    - docker push tarunk/multi-worker
