sudo: required
services:
    - docker

before_install:
    - docker build -t tarun1987/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true USERNAME/react-test npm test

after_success:
    - docker build -t tarun1987/multi-client ./client
    - docker build -t tarun1987/multi-nginx ./nginx
    - docker build -t tarun1987/multi-server ./server
    - docker build -t tarun1987/multi-worker ./worker
    # Login to docker CLI
    - echo "$DOCKER_PASSWORD" | docker -u "DOCKER_ID" --password-stdin
    # Take those images and push them to docker hub
    - docker push tarun1987/multi-client
    - docker push tarun1987/multi-nginx 
    - docker push tarun1987/multi-server
    - docker push tarun1987/multi-worker
